name: Build Macro
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  openlane-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OpenLane
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work efabless/openlane:2023.11.23-1 sh -c "flow.tcl -design . -config config.json"

      - name: Zip Artifacts
        run: |
          zip -r macro_results.zip runs/*/results/signoff/

      - name: Upload Output LEF and GDS
        uses: actions/upload-artifact@v3
        with:
          name: core-macro-files
          path: macro_results.zip
